# The MIT License (MIT)
#
# Copyright (c) 2024 Objectionary.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
docker:
  image: yegor256/rultor-image:1.23.1
assets:
  npmrc: maxonfjvipon/secrets#.npmrc
install: |
  pip install git+https://chromium.googlesource.com/external/gyp
  npm install --no-color
  sudo npm install --no-color --global grunt-cli
  npm uninstall --no-color grunt-cli
  npm install --no-color mocha
  pdd -f /dev/null -v
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/" eo2js/package.json
    sed -i "s/0\.0\.0/${tag}/" eo2js/src/version.js
    sed -i "s/0000-00-00/$(date +%Y-%m-%d)/" eo2js/src/version.js
    sed -i "s/0\.0\.0/${tag}/" eo2js-runtime/package.json
    npm test
    git commit -am "set version to ${tag}"
    chmod 600 ../npmrc
    echo "eo2js dry run:"
    (cd eo2js && npm publish --dry-run --userconfig=../../npmrc && cd ..) || exit 1
    echo "eo2js-runtime dry run:"
    (cd eo2js-runtime && npm publish --dry-run --userconfig=../../npmrc && cd ..) || exit 1
    echo "Check if eo2js exists:"
    npm view eo2js@${tag} && exit 1
    echo "Check if eo2js-runtime exists:"
    npm view eo2js-runtime@${tag} && exit 1
    echo "Publishing eo2js:"
    cd eo2js && npm publish --userconfig=../../npmrc && cd ..
    echo "Publishing eo2js-runtime:"
    cd eo2js-runtime && npm publish --userconfig=../../npmrc
merge:
  script: |-
    npm test
